### ISSUE TITLE
PHP Fatal error:  Uncaught Error: Call to private method WCS_ATT_Integrations::bundle_contains_subscription()

### ISSUE THREAD

**Issue by helgatheviking** [kathyisawesome/wc-mnm-satt-bridge#1]
>PHP Fatal error:  Uncaught Error: Call to private method WCS_ATT_Integrations::bundle_contains_subscription() from context '' in /home/ubuntu/workspace/wp-content/plugins/wc-mnm-satt-bridge/wc-mnm-satt-bridge.php:46
Stack trace:
>#0 /home/ubuntu/workspace/wp-includes/class-wp-hook.php(286): wc_mnm_satt_get_product_bundle_schemes(Array, Object(WC_Product_Bundle))
>#1 /home/ubuntu/workspace/wp-includes/plugin.php(208): WP_Hook->apply_filters(Array, Array)
>#2 /home/ubuntu/workspace/wp-content/plugins/woocommerce-all-products-for-subscriptions/includes/product/class-wcs-att-product-schemes.php(118): apply_filters('wcsatt_product_...', Array, Object(WC_Product_Bundle))
>#3 /home/ubuntu/workspace/wp-content/plugins/woocommerce-all-products-for-subscriptions/includes/product/class-wcs-att-product-schemes.php(158): WCS_ATT_Product_Schemes::get_subscription_schemes(Object(WC_Product_Bundle))
>#4 /home/ubuntu/workspace/wp-content/plugins/woocommerce-all-products-for-subscriptions/includes/product/class-wcs-att-product-schemes.php(70): WCS_A in /home/ubuntu/workspace/wp-content/plugins/wc-mnm-satt-bridge/wc-mnm-satt-bridge.php on line 46

**Comment by helgatheviking** [comment]
closed by 414be9eb90ca57fceb57ec83a10e2d85a71f0504
